baseURL = "https://guardiome.org"
languageCode = "en-us"
theme = "hello-friend-ng"

publishDir = "docs"
googleAnalytics = "UA-107909561-3"
disqusShortname = ""
[author]
  name = "Guardiome"

defaultTheme = "light"

[params]
  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  disableReadOtherPosts = false

  description = ""
  keywords = ""
  images = [""]

[permalinks]
  posts = "/projects/:year/:month/:title/"
  contentTypeName = "posts"

[languages]
  [languages.en]
    title = "Guardiome"
    subtitle = "Non-profit health analytics"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other projects"

    homeSubtitle = "Health analytics for childhood cancer patients and survivors."

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
      #path = "/img/your-example-logo.svg"
      #alt = "Your example logo alt text"

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = "1"

[[menu.main]]
    identifier = "posts"
    name = "Projects"
    url = "posts/"
    weight = "2"

[[menu.main]]
    identifier = "team"
    name = "Team"
    url = "/team"
    weight = "3"

[[params.social]]
    name = "email"
    url = "mailto:team@guardiome.org"

[[params.social]]
    name = "github"
    url  = "https://github.com/guardiome"