baseURL = "https://guardiome.org"
languageCode = "en-us"
title = "Guardiome"
themesDir = "themes"
publishDir = "docs"
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "UA-107909561-3"
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/g_only_logo_white.png"
    standard  = "images/logo_text_only_merriweather.png"
    alt = "Guardiome"

  [params.homepage_meta_tags]
    meta_description = "Health analytics for childhood cancer."
    meta_og_title = "Guardiome"
    meta_og_type = "website"
    meta_og_url = "https://guardiome.org"
    meta_og_image = ""
    meta_og_description = "Health analytics for childhood cancer."
    meta_twitter_card = "summary"
    meta_twitter_site = "@guardiome"
    meta_twitter_creator = "@guardiome"

[menu]
  # Main Menu
  
  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 1

  # Footer Menu

  [[menu.footer]]
    name = "Guardiome © 2020"
      weight = 1